In [30]:
# import librarirs

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing  import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [31]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [32]:
# separate the features X and the target/label y
x=df[['total_bill']]   # always 2d or [[]]
y=df[['tip']]

In [33]:
# split the data into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [40]:
# preprcoess the data
#scalar=StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)


In [41]:
# built the model

# call the model
model=LinearRegression()
# train the model
model.fit(x_train,y_train)

LinearRegression()

In [42]:
model.predict([[80]])

array([[73.4562392]])

In [43]:
# prediction
y_predic=model.predict(x_test)
y_predic


array([[2.34648701],
       [3.64616987],
       [2.88414741],
       [2.49302979],
       [3.76340409],
       [2.59409377],
       [2.80733878],
       [2.6961684 ],
       [2.72951952],
       [2.95792412],
       [4.30409642],
       [5.38649171],
       [2.09180576],
       [3.22271177],
       [2.64664705],
       [4.24851123],
       [4.49611799],
       [3.57744636],
       [6.1646844 ],
       [3.69872314],
       [2.99430716],
       [2.86393462],
       [3.62797835],
       [2.8305835 ],
       [2.00792265],
       [3.15297762],
       [2.04733761],
       [2.37074236],
       [2.69212584],
       [2.34345509],
       [4.52946911],
       [3.02765827],
       [2.371753  ],
       [3.03170083],
       [2.22925278],
       [2.17973143],
       [2.8406899 ],
       [2.77398767],
       [2.64159385],
       [3.45616957],
       [2.54962562],
       [5.1277679 ],
       [2.66787048],
       [4.53149039],
       [2.06957169],
       [4.33239433],
       [4.34755393],
       [3.915

In [44]:
# evaluate the model
from sklearn.metrics import mean_squared_error,r2_score
print("MSE",mean_squared_error(y_test,y_predic))
print("R2",r2_score(y_test,y_predic))

MSE 1.463069991030307
R2 0.45745552528139966


In [45]:
# save the model
import pickle
pickle.dump(model,open('./model.pkl','wb'))

In [47]:
# load the model
import pickle
model=pickle.load(open('./model.pkl','rb'))

In [48]:
model.predict([[15]])

array([[16.19962818]])